### PR TITLE
RTPEngine installation fixes on Debian

### PR DESCRIPTION
**Pull request by JoseGoncalves**

### CODE REVIEW

**Comment by pete1019** [comment]
Why does nobody care?

**Comment by devopsec** [comment]
@pete1019 adding this to review for v0.71 release

**Comment by devopsec** [comment]
> @pete1019 adding this to review for v0.71 release

This did not make the timeframe for v0.71 but will be merged into v0.72.

**Comment by devopsec** [comment]
@JoseGoncalves @pete1019 merged into https://github.com/dOpensource/dsiprouter/tree/v0.72  
Feel free to test out this branch in your environments as well.  
v0.72 is scheduled for release in march.  
Closing out this PR.

**Pull request closed without merging**
