### PR TITLE
Adds HOMER Support

### PR DESCRIPTION
**Pull request by matmurdock**

### CODE REVIEW

**Comment by matmurdock** [comment]
Adds Homer Support

**Comment by devopsec** [comment]
This would be a great addition, can you make the 'duplicate_uri' param dynamic (using a substdef) and add an install function to the install script?
If we can add this as an option during install users would certainly use it, but we should give them the option to install Homer locally and dump pcaps to the local mysql DB.
We have a function in the dsip_lib.sh script for updating kkam configs that should work for the dynamic params and enabling / disable homer on the fly

**Comment by matmurdock** [comment]
Let me get to a computer and I will look into it.

Mat

**Comment by matmurdock** [comment]
Is it wise to run Homer server on your Kamailio?  I would imagine it would be recommended to run this on a second server.

Mat

**Comment by jzrlost** [comment]
We run separate Homer servers to do the heavy lifting.  We do however run captagent on dsiprouter to pass the HEP to the Homer servers.  I read there is a native way to pass the HEP from Kamailio (dsiprouter's core) to a remote Homer server.  Is that in the Kamailio conf file?  I would love to not have to install separate software.

**Comment by matmurdock** [comment]
Add this in the Module Specific Parameters section
# ----- HOMER params -----
# check IP and port of your capture node
modparam("siptrace", "duplicate_uri","sip:172.16.10.26:9060");
modparam("siptrace", "hep_mode_on", 1);
modparam("siptrace", "trace_to_database", 0);
modparam("siptrace", "trace_flag", 22);
modparam("siptrace", "trace_on", 1);
modparam("siptrace", "hep_version", 3)


Add this right after the "request_route {" line.

#start duplicate the SIP message now
sip_trace();
setflag(22);

Good luck.

Mat

**Comment by jzrlost** [comment]
Does it matter where in Module Specific Parameters section I had the code?  I added it right before the next section (routing logic) and Kamailio won't start.  If I comment it all out then it starts again.

**Comment by matmurdock** [comment]
Look at this example. 

https://github.com/dOpensource/dsiprouter/blob/3e0365ca1192e5bae5f775b27c541c1320076d87/kamailio/kamailio51_dsiprouter.tpl

**Comment by jzrlost** [comment]
Followed the example and got everything added and Kamailio started.  Doesn't seem to be pushing data to the Homer server though.  I will let it run tomorrow and check the Homer logs to see if any of the traffic is picked up.  Didn't see anything incoming when checking the traffic on port 9060 though.

**Comment by matmurdock** [comment]
You did update the IP correct?

Mat

**Comment by jzrlost** [comment]
Yes, changed the IP to the Homer server.

**Comment by matmurdock** [comment]
In the example I sent it requires you a define entry up at the top.  Add
"#!define WITH_HOMER"

Mat

**Comment by jzrlost** [comment]
If I put the "#!define WITH_HOMER" at the top like the example file, Kamailio does not start.

**Comment by jzrlost** [comment]
When I run the "systemctl status kamailio.service" the first error is "ERROR: <core> [core/cfg.y:3323]: yyparse(): cfg. parser: failed to find command sip_trace (params 0)"  Not sure if that helps or not.

**Comment by matmurdock** [comment]
I will be doing a clean install tomorrow. I will see what is missing.  BTW,
what OS are you using?

Mat

**Comment by jzrlost** [comment]
So I added "loadmodule "siptrace.so" to the kamailio config and now I see HEP3 packets coming from dsiprouter.  I will continue to test and see how it goes.

**Comment by matmurdock** [comment]
Ah, yeah that makes sense.  :)

Mat

**Comment by jzrlost** [comment]
I am using Ubuntu 16.04.  So far so good.  Made some test calls and all it working. The only thing that is not showing in Homer is the Call Statistics.  Does this way within Kamailio only transfer the SIP signaling or does it track RTCP also?  The captagent had a separate config for the RTCP traffic to be passed.  Also, I am assuming that if I want to track the RTP I have to somehow get RTPengine to transfer HEP to Homer also?

**Comment by matmurdock** [comment]
I don't know the answer that.  I wonder if you have to proxy the rtp
traffic in order to get that information.

Mat

**Comment by jzrlost** [comment]
I do proxy RTP through dsiprouter.  I can see the RTP and RTCP traffic in sngrep when making a call.  Just need to figure out how to get RTPengine to pass what's need to Homer and match it up with the correct calls.

**Pull request closed without merging**
