### PR TITLE
Multi-Home support for hosted PBX

### PR DESCRIPTION
**Pull request by matmurdock**
This takes into case more use cases as to how to route a call. We are using this in production. The only gotcha is if there is an external device added as a PBX that has the same IP as one of the extensions.

### CODE REVIEW

**Comment by devopsec** [comment]
changed base to dev for your pull requests, we will review as soon as we can.

**Comment by devopsec** [comment]
What is does your environment look like for this build Matt?
I would like to replicate on our end so we can confirm this as a resolution and get it committed in.

I noticed the removal of DLGURI and SIPOUT route as well I believe the 'P-hint: outbound' header is required for routing elsewhere in the route logic.
Why do we need to remove in dialog alias handling as well?

**Comment by matmurdock** [comment]
It was a mistake to remove DLGURI and SIPOUT.  I have fixed the patch.
Looks a little ugly.  I have attached an image of our setup below.
Hopefully you can see it.

Mat

[image: image.png]

**Comment by matmurdock** [comment]
Try accessing the image here: [Picture](https://drive.google.com/open?id=1l6pCWSuaEuetK9TKu8P26nJSet5Xpium)

Mat

**Comment by devopsec** [comment]
thanks Matt, I will test this out on our end and get back to you.
One suggestion I have is changing the WITH_PROXY_ALLRTP define to a conditional, which would be more flexible.
For example,
If we know that the incoming IP is external and outgoing IP is internal then we set FLG_NATS:
if (! is_rfc1918(src_ip)) && (is_rfc1918(dst_ip)) {
...
setflag(FLT_NATS);
...
}

**Comment by matmurdock** [comment]
Huh.  is_rfc1981(), might be able to use that in a few places.

Mat

**Comment by mackhendricks** [comment]
This has been merged into the feature-multihome branch.  It's on target to be pushed into v0.522 release.

**Pull request closed without merging**
